# === paucal.toml ===
# For all of my Minecraft mods.
# This is loaded by my library mod PAUCAL on game startup.

# https://gameplay.tools/minecraft/uuid
# sadly has people's deadnames on it :(

# petra_the_kat
["a2ce9382-2518-4752-87b2-c6a5c97f173e"]
"paucal:contributor_level" = 7604
"paucal:is_dev" = true

"paucal:pat_sound" = "bwop"
"paucal:pat_variance" = 0.1

# colorizer = [0xebad1c, 0xc7c7bd, 0x7c2e94, 0x2e060f]

# Dev (the forge dummy player)
["380df991-f603-344c-a090-369bad2a924a"]
"paucal:contributor_level" = 4 # for testing purposes
"paucal:is_dev" = true

"paucal:pat_sound" = "minecraft:block.note_block.bit"
"paucal:pat_variance" = 0.1

